version: "3"
services:
  # tipxmr-frontend:
  #   container_name: "tipxmr-frontend"
  #   build: 
  #     context: ./projects/tipxmr-frontend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./projects/tipxmr-frontend:/app
  #     - exclude-fe:/app/node_modules
  #   networks:
  #     - tipxmr_network
  #   command: npm run start

  tipxmr-backend:
    container_name: "tipxmr-backend"
    build: 
      context: ./projects/tipxmr-backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./projects/tipxmr-backend:/usr/app
      - exclude-be:/usr/app/node_modules/
    networks:
      - tipxmr_network
    depends_on: 
      - "db"
    environment:
      - DB_HOST=postgres

  # monero-node:
  #   container_name: "monero-node"
  #   platform: linux/amd64
  #   build:
  #     context: ./projects/monero-node
  #   command: --non-interactive --config-file /home/monero/.bitmonero/stagenet.conf
  #   ports:
  #     - "38080:38080"
  #     - "38081:38081"
  #   volumes:
  #     - ./projects/monero-node/bitmonero:/home/monero/.bitmonero
  #   networks:
  #     - tipxmr_network
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: 10m
  #       max-file: "3"

  db:
    container_name: "tipxmr-db"
    hostname: postgres
    image: postgres:latest
    command: postgres -c stats_temp_directory=/tmp
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=tipxmr
      - POSTGRES_USER=tipxmr
      - POSTGRES_PASSWORD=tipxmr
    networks:
      - tipxmr_network

  pgadmin:
    container_name: "tipxmr-pgadmin"
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tipxmr.live
      PGADMIN_DEFAULT_PASSWORD: tipxmr
    restart: unless-stopped
    networks:
      - tipxmr_network

volumes: 
  # exclude-fe:
  exclude-be:

networks:
  tipxmr_network: 
    driver: bridge