version: "3"
services:
  tipxmr-frontend:
    container_name: "tipxmr-frontend"
    build: 
      context: ./projects/tipxmr-frontend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: npm start
    volumes:
      - ./projects/tipxmr-frontend:/usr/local/app
      - exclude-fe:/usr/local/app/node_modules/

  tipxmr-backend:
    container_name: "tipxmr-backend"
    build: 
      context: ./projects/tipxmr-backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run watch
    volumes:
      - ./projects/tipxmr-backend:/usr/local/app
      - exclude-be:/usr/local/app/node_modules/

  monero-node:
    container_name: "monero-node"
    build:
      context: ./projects/monero-node
    command: --non-interactive --config-file /home/monero/.bitmonero/stagenet.conf
    ports:
      - "38080:38080"
      - "38081:38081"
    volumes:
      - ./projects/monero-node/bitmonero:/home/monero/.bitmonero
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
volumes: 
  exclude-fe:
  exclude-be: